---
# This playbook will ensure that all ipaClients are ready for joining IPA

- name: Ensure that all Fedora 34 systems are ready for IPA Join
  hosts: psqlServers
  become: yes
  tasks:

    - name: Ensure that the FreeIPA Client is installed
      ansible.builtin.dnf:
        name: postgresql
        state: latest
    - name: Ensure that Postgres is running and enabled
      ansible.builtin.systemd:
        name: postgresql
        state: started
        enabled: yes