---
# This playbook will ensure that all fedora34 machines are up to date

- name: Ensure that all Fedora 34 systems are ready for IPA Join
  hosts: fedora34
  become: yes
  tasks:

    - name: Ensure that all packages are the latest version
      ansible.builtin.dnf:
        name: "*"
        state: latest
